name: "Push Playit Binary to Cachix"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "flake.lock"
      - "packages/playit.nix"

permissions:
  contents: read

jobs:
  eval-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.eval-matrix.outputs.matrix }}
    steps:
      - name: Setup job
        uses: pedorich-n/github-workflows/.github/actions/setup-nix-job@394fb5dff4f8ee88f7fec2c55bb178875af055c5 # main

      - name: Evaluate matrix
        id: eval-matrix
        shell: bash
        run: |
          matrix=$(nix eval --json .#ghaMatrices.cache.matrix)
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  upload-cachix:
    name: ${{ matrix.name }} (${{ matrix.system }})
    needs: eval-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJSON(needs.eval-matrix.outputs.matrix) }}
    steps:
      - name: Setup job
        uses: pedorich-n/github-workflows/.github/actions/setup-nix-job@394fb5dff4f8ee88f7fec2c55bb178875af055c5 # main

      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: playit-nixos-module
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build and push to Cachix
        run: nix build .#${{ matrix.attr }} --accept-flake-config --print-out-paths
