name: Nix Flake Check
on: push

permissions:
  contents: read

jobs:
  nix-flake-check:
    uses: pedorich-n/github-workflows/.github/workflows/flake-check.yaml@58548fbbf0d64500d5d3dd8adfe95ab60dca44fb # main
