name: Nix Flake Check
on: push

permissions:
  contents: read

jobs:
  nix-flake-check:
    uses: pedorich-n/github-workflows/.github/workflows/flake-check.yaml@87e04487a67351351bfbbd2670ea74763bf89f13 # main
