name: Update Packages' Sources

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 1 * *"

permissions:
  contents: read

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Get Github App info
        id: app_auth
        uses: pedorich-n/github-workflows/.github/actions/app-token@394fb5dff4f8ee88f7fec2c55bb178875af055c5 # main
        with:
          client_id: ${{ vars.APP_CLIENT_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Setup job
        uses: pedorich-n/github-workflows/.github/actions/setup-nix-job@394fb5dff4f8ee88f7fec2c55bb178875af055c5 # main

      - name: Run nix-update
        uses: pedorich-n/github-workflows/.github/actions/nix-update@394fb5dff4f8ee88f7fec2c55bb178875af055c5 # main
        with:
          token: ${{ steps.app_auth.outputs.token }}
          committer: ${{ steps.app_auth.outputs.committer }}
          author: ${{ steps.app_auth.outputs.committer }}
          packages: playit
