name: Update Packages' Sources

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 1 * *"

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Get Github App info
        id: app_auth
        uses: pedorich-n/github-workflows/.github/actions/app-token@ab0b55f0c919123865d500485c7a275c487e6466 # main
        with:
          client_id: ${{ vars.APP_CLIENT_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Setup job
        uses: pedorich-n/github-workflows/.github/actions/setup-nix-job@ab0b55f0c919123865d500485c7a275c487e6466 # main

      - name: Run nix-update
        uses: pedorich-n/github-workflows/.github/actions/nix-update@ab0b55f0c919123865d500485c7a275c487e6466 # main
        with:
          token: ${{ steps.app_auth.outputs.token }}
          committer: ${{ steps.app_auth.outputs.committer }}
          author: ${{ steps.app_auth.outputs.committer }}
          packages: playit
